version: '2'
services:
   web:
      container_name: server-api-flask
      hostname: server-api-flask
      build: .
      ports:
         - "5000:5000"
      volumes:
         - .:/code
      networks:
         - stocksb3-net

networks:
  stocksb3-net:
    driver: bridge
